trigger:
  branches:
    include:
    - main
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install, build, and test'
      inputs:
        script: |
          npm install
          npm run build --if-present
          npm run test --if-present
    - task: CmdLine@2
      displayName: 'Zip artifact for deployment'
      inputs:
        script: |
          zip -r release.zip ./*
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'node-app'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn:
  - Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure Web App'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Sparc-Azure'
        appType: 'webAppLinux'
        WebAppName: 'app-sparc-dev-wus-002'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'